# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160227_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(default='yes it is test'),
            preserve_default=False,
        ),
    ]
