# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='qoute',
            new_name='quote',
        ),
    ]
