# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160318_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
